### PR TITLE
docs(wallet): fix misleading RBF comment in `create_tx`

### LINKED ISSUE #45: Fix docs for Wallet:create_tx when empty output vector
"In Wallet::create_tx when the outputs vector of the transaction is empty, you have a comment "We have a drain_to address and the utxos we must spend (this happens, for example, when we RBF)" which seems misleading to me. If by "when we RBF" you mean what build_fee_bump does, then it's incorrect as build_fee_bump won't set params.drain_to."

### PR DESCRIPTION
**Pull request by va-an**
### Description

Fix misleading comment in `create_tx` regarding empty tx output logic. This addresses a documentation nitpick brought up by the 2024 [WizardSardine report](https://bitcoindevkit.org/audits/2024_q4/bdk_audit_report).

- Replaced incorrect RBF example with sweeping UTXOs
- Reordered comment items to match the code's condition order

Closes #45 

### Changelog notice

Fixed:
- Fix docs for `Wallet:create_tx` when empty output vector

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `just p` before pushing

### CODE REVIEW

**Comment by ValuedMammal** [comment]
ACK 62409a5bfe3efa23c265a4f15892837e6b241d01 I agree the comment was confusing and at least now it better describes what the code is doing.

**Review by ValuedMammal — APPROVED** [review]

File: src/wallet/mod.rs [hunk 1]
```diff
@@ -1492,10 +1492,10 @@ impl Wallet {
...
         if tx.output.is_empty() {
             // Uh oh, our transaction has no outputs.
-            // We allow this when:
-            // - We have a drain_to address and the utxos we must spend (this happens,
-            // for example, when we RBF).
-            // - We have a drain_to address and drain_wallet set.
+            // We allow this when we have a `drain_to` address and either:
+            // - `drain_wallet` is enabled
+            // - there are utxos we must spend (this happens, for example, when
+            // sweeping specific UTXOs to a given address)
```
Comment (luisschwab) [inline src/wallet/mod.rs:1498]: nit: be consistent with the line below

```suggestion
            // We allow this when we have a `drain_to` address and either:
            // - `drain_wallet` is enabled
            // - there are UTXOs we must spend (this happens, for example, when
            // sweeping specific UTXOs to a given address)
```

**Review by luisschwab — CHANGES_REQUESTED** [review]

**Comment by luisschwab** [comment]
Can you squash the commits?

**Review by luisschwab — APPROVED** [review]
ACK 76a8cc6da25fcc40dc17cd29b4ca5677d47a604f
