### PR TITLE
Preserve insertion order of manually selected utxos if `TxOrdering::Untouched`

### LINKED ISSUE #244: TxOrdering::Untouched no longer ensures the order of tx input
**Describe the bug**  
Since add_utxo of build_tx in 1.2.0 uses hashmap to contain input, TxOrdrering cannot ensure that the order is not changed.

**To Reproduce**  
```rust
    let utxos = wallet1
        .list_unspent()
        .map(|o| o.outpoint)
        .collect::<Vec<_>>();
    let builder = wallet1.build_tx();
    builder
        .ordering(bdk_wallet::TxOrdering::Untouched)
        .fee_rate(FeeRate::from_sat_per_vb(5).unwrap())
        .add_utxo(utxos[0])
        .unwrap()
        .add_utxo(utxos[1])
        .unwrap()
        .add_recipient(
            wallet1.peek_address(External, 0).address.script_pubkey(),
            bitcoin::Amount::from_sat(1000),
        );

    let inputs = builder.finish().unwrap().unsigned_tx.input;
    // can't assert
    assert!(inputs[0].previous_output == utxos[0]);
    assert!(inputs[1].previous_output == utxos[1]);
```

**Expected behavior**  
```rust
    assert!(inputs[0].previous_output == utxos[0]);
    assert!(inputs[1].previous_output == utxos[1]);
```

**Build environment**  
 - BDK tag/commit: 1.2.0
 - OS+version:   
 - Rust/Cargo version: *
 - Rust/Cargo target: *

**Additional context**  
https://github.com/bitcoindevkit/bdk_wallet/blob/5817ed07f220c787a26e234307f8308d3ab6165e/crates/wallet/src/wallet/tx_builder.rs#L128

### PR DESCRIPTION
**Pull request by nymius**
### Description

On my attempt to fix bitcoindevkit/bdk#1794 in bitcoindevkit/bdk#1798, I broke the assumption that insertion order is preserved when `TxBuilder::ordering` is `TxOrdering::Untouched`. Some users are relying in this assumption, so here I'm trying to restore it back, without adding a new dependency for this single use case like #252, or creating a new struct just to track this.

In this fourth alternative solution I'm going back to use `Vec` to store the manually selected UTxOs.

I was reluctant to do it in this way because `HashMap` seems a better solution giving its property of avoiding duplicates, but as we also want to keep the secuential nature of the insertion of UTxOs in `TxBuilder`, here is an alternative aligned with that principle. 

May replace #252 
May replace #261 .
Fixes #244

### Notes to the reviewers

Also, as I was working on this, I came back to the following tests:
- `test_prexisting_foreign_utxo_have_no_precedence_over_local_utxo_with_same_outpoint`
- `test_prexisting_local_utxo_have_precedence_over_foreign_utxo_with_same_outpoint`

Motivated during the implementation and review of bitcoindevkit/bdk#1798.

Which required the underlying structure to also hold the properties of no duplication for manually selected UTxOs, as the structures were accessed directly for these cases.

The test tries to cover the case when there are two wallets using the same descriptor, one tracks transactions and the other does not. The first passes UTxOs belonging to the second one and this one creates transactions using the `add_foreign_utxo` interface.
In this case it was expected for any `LocalUtxo` of the offline wallet to supersede any conflicting foreign UTxO. But, the simulation of this case went against the borrowing constraints of rust.
By how costly was to reproduce this behavior for me in the tests, I would like to have second opinions in the feasibility of the test case.

### Changelog notice

No public APIs are changed by these commits.

### Checklists

> [!IMPORTANT]
> This pull request **DOES NOT** break the existing API
* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo +nightly fmt` and `cargo clippy` before committing
* [x] I've added tests for the new code
* [x] I've expanded docs addressing new code
* [x] I've added tests to reproduce the issue which are now passing
* [x] I'm linking the issue being fixed by this PR

### CODE REVIEW

File: wallet/src/wallet/tx_builder.rs [hunk 1]
```diff
@@ -276,29 +276,31 @@ impl<'a, Cs> TxBuilder<'a, Cs> {
...
+            };
+
+            if let Some(idx) = self.params.utxos.iter().position(|wutxo| match wutxo.utxo {
+                Utxo::Local(LocalOutput { outpoint, .. }) => outpoint == *recv_outpoint,
+                Utxo::Foreign { outpoint, .. } => outpoint == *recv_outpoint,
+            }) {
+                self.params.utxos.remove(idx);
+            }
+            self.params.utxos.push(wutxo);
+        }
```
[the remark this answers is not in the document]
Comment (nymius) [reply wallet/src/wallet/tx_builder.rs:303]: To bring back the original rationale about why favor precedence of new UTxOs over old ones, https://github.com/bitcoindevkit/bdk/pull/1798/files#r1974774295:
> Ideally, we would error here if an `OutPoint` conflicts with a foreign UTXO. However, we will need to add new error variants (which is a MAJOR change since the error type does not have `non-exhaustive`).
> 
> For now, how about we make a note in the docs that if you add the same UTXO as both foreign and local, the latest change has precedence (please word that better).
> 
> Same goes for the add-foreign-utxo methods.

In the light of the above comment, do you think we should still roll back to the old precedence @ValuedMammal? @evanlinjin do you have any opinion on this?

I think we still prefer `Utxo::Local` over `Utxo::Foreign`.

[the remark this answers is not in the document]
Comment (ValuedMammal) [reply wallet/src/wallet/tx_builder.rs:303]: I guess that would work too.

File: wallet/src/wallet/tx_builder.rs [hunk 2]
```diff
@@ -276,29 +276,45 @@ impl<'a, Cs> TxBuilder<'a, Cs> {
...
-                                    .wallet
-                                    .public_descriptor(output.keychain)
-                                    .max_weight_to_satisfy()
-                                    .unwrap(),
-                                utxo: Utxo::Local(output),
-                            },
-                        )
-                    })
+            .map(|&op| -> Result<_, AddUtxoError> {
+                visited.insert(op);
```
Comment (ValuedMammal) [inline wallet/src/wallet/tx_builder.rs:295]: I still think we should avoid creating more of the same `WeightedUtxo` if the outpoint is already visited.

```suggestion
            .filter(|&&op| visited.insert(op))
            .map(|&op| -> Result<_, AddUtxoError> {
```

For example how should tx builder behave in this situation?

```rs
    let (mut wallet, _) = get_funded_wallet_wpkh();
    let utxo = wallet.list_unspent().next().unwrap();
    let op = utxo.outpoint;

    let mut tx_builder = wallet.build_tx();
    tx_builder.add_utxos(&[op, op, op]).unwrap();

    assert_eq!(tx_builder.params.utxos.len(), 1);
```

File: wallet/src/wallet/tx_builder.rs [hunk 3]
```diff
@@ -407,25 +427,32 @@ impl<'a, Cs> TxBuilder<'a, Cs> {
...
 
-        if let Some(WeightedUtxo {
-            utxo: Utxo::Local { .. },
-            ..
-        }) = self.params.utxos.get(&outpoint)
-        {
-            None
-        } else {
-            self.params.utxos.insert(
+        let mut collisioning_foreign_utxo_idx: Option<usize> = None;
```
Comment (ValuedMammal) [inline wallet/src/wallet/tx_builder.rs:430]: Naming nit
```suggestion
        let mut existing_index: Option<usize> = None;
```

File: wallet/tests/wallet.rs [hunk 4]
```diff
@@ -4699,3 +4699,73 @@ fn test_tx_details_method() {
...
+        &mut wallet,
+        txid1,
+        ConfirmationBlockTime {
+            block_id: BlockId {
+                height: 2_100,
+                hash: BlockHash::all_zeros(),
+            },
+            confirmation_time: 300,
+        },
+    );
```
Comment (ValuedMammal) [inline wallet/tests/wallet.rs:4737]: For this to make sense you should also insert a checkpoint into the local chain, but for this test I think `insert_tx` on its own is sufficient.

**Review by ValuedMammal — CHANGES_REQUESTED** [review]
For consistency with the rest of the codebase I want to stick with the "UTXO" style acronym.

**Review by ValuedMammal — APPROVED** [review]
ACK d6d204bfe15b0ac643f9abc0b8edb74cda391a04

File: wallet/src/wallet/mod.rs [hunk 5]
```diff
@@ -2117,8 +2115,9 @@ impl Wallet {
                         .then(|| new_local_utxo(k, i, full_txo))
                 })
                 // only process UTxOs not selected manually, they will be considered later in the
-                // chain NOTE: this avoid UTxOs in both required and optional list
-                .filter(|may_spend| !params.utxos.contains_key(&may_spend.outpoint))
+                // chain
+                // NOTE: this avoid UTxOs in both required and optional list
```
Comment (oleonardolima) [inline wallet/src/wallet/mod.rs:2119]:
``` suggestion
                // chain
                // NOTE: this avoid UTXOs in both required and optional list
```

**Review by oleonardolima — COMMENTED** [review]
utACK

I left a question and a single nit, but overall it looks good to me! Agree with the new version of test suggested by VM's, it looks much better.

File: wallet/src/wallet/tx_builder.rs [hunk 6]
```diff
@@ -407,25 +421,32 @@ impl<'a, Cs> TxBuilder<'a, Cs> {
...
+                        existing_index = Some(idx);
+                        break;
+                    }
+                }
+            }
+        }
+
+        if let Some(idx) = existing_index {
+            self.params.utxos.remove(idx);
+        }
```
[the remark this answers is not in the document]
Comment (nymius) [reply wallet/src/wallet/tx_builder.rs:446]: The idea is to only keep the latest item on conflict foreign or local). Locals can override foreign and local in case of conflict, but foreign can only override foreign. That's what this line is doing, removing the old conflicting foreign utxo.

The documentation is addressing this behavior now:
> /// Foreign UTXOs are not prioritized over local UTXOs. If a local UTXO is added to the
> /// manually selected list, it will replace any conflicting foreign UTXOs. However, a foreign
> /// UTXO cannot replace a conflicting local UTXO.

**Review by oleonardolima — APPROVED** [review]
ACK 0522114aa17c788d952ac60db8b26cb08ad1d871
